# Generated by Django 5.0.8 on 2024-08-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_remove_empleado_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
